data_path: /scratch/up63/kd6504/recbole_datasets

field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
POSITION_FIELD: position_id

load_col:
  inter: [user_id, item_id, rating, timestamp]

unused_col:
  inter: [rating]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

MAX_ITEM_LIST_LENGTH: 50

seed: 2026
reproducibility: true
show_progress: False

model: LightSANs

loss_type: CE

hidden_size: 64
inner_size: 256
n_layers: 2
n_heads: 2
k_interests: 5
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: gelu
layer_norm_eps: 1e-12
initializer_range: 0.02

epochs: 200
train_batch_size: 128
learner: adam
learning_rate: 0.001
train_neg_sample_args: null
eval_step: 1
weight_decay: 0.0
clip_grad_norm: null

valid_metric: NDCG@10
stopping_step: 10
eval_batch_size: 4096

eval_args:
  split: {"LS": "valid_and_test"}
  order: TO
  group_by: user
  mode: {"valid": "full", "test": "full"}

metrics: ["Hit", "NDCG", "MRR", "Recall"]
topk: [10]

checkpoint_dir: outputs/lightsans_ml1m
